server:
  address: 0.0.0.0
  port: 8888
peer: #port et adresse de B
  address: localhost
  port: 8887
files_list: 'b.txt' # liste des fichiers de streaming
remote_files_list: 'b.txt'   #liste des fichiers de streaming partagé avec B
